name: Orchestrate Workflow Runs

on:
    workflow_dispatch:
      inputs:
        google_sheet_id:
          description: 'ID of the Google Sheet containing repository links.'
          required: true
        links_tab_name:
          description: 'Title of the tab containing the links.'
          required: true
        pro_github_repositories:
          description: 'Space-separated list of pro GitHub repositories in the format owner/repo-name.'
          required: true
        reg_github_repositories:
          description: 'Space-separated list of regular GitHub repositories in the format owner/repo-name.'
          required: false
        release_name:
          description: 'Name of the release to be created.'
          default: all-results-2024-05-18-morning
          required: true

jobs:
    prepare-and-trigger:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
  
      - name: Install jq
        run: sudo apt-get install jq
  
      - name: Prepate github repos
        id: encode-decode
        run: |
          echo "${{ github.event.inputs.pro_github_repositories }}" > pro_github_repos.txt
          echo "${{ github.event.inputs.reg_github_repositories }}" > regular_github_repos.txt
      
      - name: Install Dependencies
        run: pip3 install pygsheets PyGithub
  
      - name: Prepare Chunks and Populate Tabs
        id: prepare-chunks
        run: python3 scripts/manage_links.py
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
            GOOGLE_SHEET_ID: ${{ github.event.inputs.google_sheet_id }}
            LINKS_TAB_NAME: ${{github.event.inputs.links_tab_name}}
  
      - name: Trigger Workflows on Pro Repos
        run: python3 scripts/trigger_workflows.py
        env:
            GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
            GOOGLE_SHEET_ID: ${{ github.event.inputs.google_sheet_id }}
            CHUNK_COUNT: ${{ steps.prepare-chunks.outputs.pro_chunk_count }}
            RELEASE_NAME: ${{ github.event.inputs.release_name }}
            PREFIX: 'pro_links_chunk_'
            REPOS_FILE_NAME: 'pro_github_repos.txt'

      - name: Trigger Workflows on Regular Repos
        run: python3 scripts/trigger_workflows.py
        env:
            GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
            GOOGLE_SHEET_ID: ${{ github.event.inputs.google_sheet_id }}
            CHUNK_COUNT: ${{ steps.prepare-chunks.outputs.reg_chunk_count }}
            RELEASE_NAME: ${{ github.event.inputs.release_name }}
            PREFIX: 'reg_links_chunk_'
            REPOS_FILE_NAME: 'regular_github_repos.txt'
  